import { chromium, expect } from '@playwright/test';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { unzipSync } from 'fflate';
const base = process.env.LIBRARY_TEST_URL || 'http://127.0.0.1:8794';
const output = path.resolve('artifacts/browser');
await fs.mkdir(output, { recursive: true });
const browser = await chromium.launch({ channel: 'msedge', headless: true });
const errors = [];
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ['clipboard-read', 'clipboard-write'], acceptDownloads: true });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base, { waitUntil: 'networkidle' });
  await expect(page.locator('.skill-card')).toHaveCount(24);
  assert.ok((await (await fetch(`${base}/api/health`)).json()).skills > 2000);
  await page.screenshot({ path: path.join(output, 'desktop.png'), fullPage: true });
  const search = page.getByRole('textbox', { name: 'Search skills by name or description' });
  await page.keyboard.press('/'); await expect(search).toBeFocused();
  await search.fill('hyperframes-core');
  await page.locator('.skill-card .card-main').first().click();
  await expect(page.locator('dialog')).toBeVisible();
  await expect(page.locator('dialog .markdown')).toContainText('Hyper');
  await page.getByRole('button', { name: 'Copy skill', exact: true }).click();
  assert.match(await page.evaluate(() => navigator.clipboard.readText()), /name:\s*hyperframes-core/);
  await page.getByRole('button', { name: 'Claude', exact: true }).click();
  await expect(page.locator('.install-panel .code-block')).toContainText('--agent claude');
  const skillId = new URL(page.url()).pathname.split('/').at(-1);
  const manifest = await (await fetch(`${base}/manifests/${skillId}.json`)).json();
  const downloaded = page.waitForEvent('download');
  await page.getByRole('link', { name: /Download ZIP/ }).click();
  const download = await downloaded;
  const archive = path.join(output, download.suggestedFilename());
  await download.saveAs(archive);
  const zip = await fs.readFile(archive), entries = unzipSync(zip);
  assert.equal(createHash('sha256').update(zip).digest('hex'), manifest.archiveSha256);
  assert.equal(Object.keys(entries).length, manifest.files.length + 1);
  assert.ok(Object.keys(entries).some(name => name.endsWith('/SKILL.md')));
  await page.screenshot({ path: path.join(output, 'skill-detail.png') });
  await page.getByRole('button', { name: 'Save skill', exact: true }).click();
  await page.keyboard.press('Escape');
  await expect(page.locator('dialog')).toHaveCount(0);
  await search.fill('');
  await page.locator('.filters').getByRole('button', { name: /Saved skills/ }).click();
  await expect(page.locator('.skill-card')).toHaveCount(1);
  await page.reload(); await page.locator('.skill-card').first().waitFor();
  await page.locator('.filters').getByRole('button', { name: /Saved skills/ }).click();
  await expect(page.locator('.skill-card')).toHaveCount(1);
  await page.getByRole('button', { name: 'Discover', exact: true }).click();
  await search.fill('zzqqqnotfound987654321');
  await expect(page.getByRole('heading', { name: 'No skills found yet.' })).toBeVisible();
  await page.getByRole('button', { name: 'Explore skills', exact: true }).click();
  await expect(page.locator('.skill-card')).toHaveCount(24);
  await page.getByRole('button', { name: /For agents/ }).click();
  await expect(page.locator('dialog')).toContainText('MCP');
  await page.keyboard.press('Escape');
  await page.route('**/api/submissions', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Submission test unavailable.' }) }));
  await page.getByRole('button', { name: 'Submit a skill', exact: true }).click();
  await page.getByLabel('GitHub repository', { exact: true }).fill('https://github.com/example/skill-example');
  await page.getByLabel('Skill folder in the repository', { exact: true }).fill('skills/testing');
  await page.getByRole('button', { name: 'Submit for review' }).click();
  await expect(page.getByRole('alert')).toContainText('Submission test unavailable.');
  await page.unroute('**/api/submissions');
  await page.route('**/api/submissions', route => route.fulfill({ status: 202, contentType: 'application/json', body: JSON.stringify({ id: 'browser-ui-fixture', status: 'pending', message: 'Fixture queued for review.' }) }));
  await page.getByRole('button', { name: 'Submit for review' }).click();
  await expect(page.getByRole('heading', { name: 'Added to the review queue.' })).toBeVisible();
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, deviceScaleFactor: 1 });
  const mobilePage = await mobile.newPage(); mobilePage.on('pageerror', error => errors.push(error.message));
  await mobilePage.goto(base, { waitUntil: 'networkidle' }); await mobilePage.locator('.skill-card').first().waitFor();
  assert.ok(await mobilePage.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'Mobile page must not overflow horizontally');
  await mobilePage.screenshot({ path: path.join(output, 'mobile.png'), fullPage: true });
  await mobilePage.getByRole('button', { name: 'Filters', exact: true }).click();
  await expect(mobilePage.locator('.filters')).toBeVisible();
  await mobilePage.locator('.filters').getByRole('button', { name: /Video & audio/ }).click();
  await expect(mobilePage.locator('.filters')).not.toBeVisible();
  await expect(mobilePage.getByRole('heading', { name: 'Video & audio', exact: true })).toBeVisible();
  await mobilePage.locator('.skill-card .card-main').first().click();
  await expect(mobilePage.locator('dialog .download-button')).toBeVisible();
  assert.ok(await mobilePage.locator('dialog').evaluate(element => element.scrollWidth <= element.clientWidth), 'Mobile detail must fit');
  assert.deepEqual(errors, []);
  const report = { status: 'passed', desktop: true, mobile: true, search: true, keyboardShortcut: true, skillPreview: true, clipboard: true, zipHashes: true, bookmarkPersistence: true, emptyState: true, submissionSuccessAndFailureUi: true, browserErrors: errors };
  await fs.writeFile(path.join(output, 'result.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify(report));
} finally { await browser.close(); }
